### ISSUE TITLE
과제 02 이슈

### ISSUE THREAD

**Issue by EthanSeok** [nayoung2da/ppp2024#1]
## 과제 02 이슈
* 계산 실수

## 코멘트
```python
#hw04
base = 5
upper_side = 3
height = 4
trapezoid = base + upper_side * height / 2
print("사다리꼴의 넓이 : {}".format(trapezoid))

# 출력값: 11.0
```

* `trapezoid = base + upper_side * height / 2`에서 `trapezoid = (base + upper_side) * height / 2`로 수정하여야 정상적으로 계산됩니다.  나영 학생이 제시한 코드는 `upper_side * height / 2`이 선행적으로 계산되어 결과가 달라진 것으로 보입니다. 프로그래밍에서 수식을 다룰 때는 `()` 사용에 주의하여야 합니다. 수고하셨습니다~

**Comment by nayoung2da** [comment]
넵 확인했습니다! 감사합니다~
