### ISSUE TITLE
과제 04 이슈

### ISSUE THREAD

**Issue by EthanSeok** [nayoung2da/ppp2024#2]
## 과제 03 및 04 이슈
* 파일 이름 특수문자

## 코멘트
* `hw03_kcal_dict+.py`와 같이 파일명에 `언더바(_)`를 제외한 특수기호 `+`를 붙이면 문제가 생길 수 있습니다. 단순 코드 실행에는 문제가 없지만 파일을 모듈화하여 사용할 시에 문제가 될수 있습니다. 되도록이면 파이썬 파일명에 특수문자 사용을 지양하는 것을 권장합니다.

**Comment by nayoung2da** [comment]
넵 확인했습니다. hw03_kcal_dict_plus.py로 변경하겠습니다. 감사합니다.
